### ISSUE TITLE
Since this morning: `Request failed: An update to Mazda app is required to continue` for any request

### ISSUE THREAD

**Issue by HWiese1980** [bdr99/pymazda#20]
Hi,

since today morning I'm receiving the error `Request failed: An update to Mazda app is required to continue` for all and any request sent to the MyMazda API. Seems like Mazda has updated their end and pymazda got to follow along.

Just for info...

Cheers!

**Comment by pr0fetul** [comment]
Hi Brandon (@bdr99 )
It seems that there is another MyMazda update that's needed.
Can you re-update the code?
```
Logger: homeassistant.components.mazda
Source: components/mazda/__init__.py:43
Integration: Mazda Connected Services (documentation, issues)
First occurred: 3:03:19 AM (108 occurrences)
Last logged: 8:24:48 AM

Unknown error occurred during Mazda update request: Request failed: An update to Mazda app is required to continue
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mazda/__init__.py", line 148, in async_update_data
    vehicle["status"] = await with_timeout(
  File "/usr/src/homeassistant/homeassistant/components/mazda/__init__.py", line 43, in with_timeout
    return await task
  File "/usr/local/lib/python3.9/site-packages/pymazda/client.py", line 64, in get_vehicle_status
    vehicle_status_response = await self.controller.get_vehicle_status(vehicle_id)
  File "/usr/local/lib/python3.9/site-packages/pymazda/controller.py", line 31, in get_vehicle_status
    response = await self.connection.api_request("POST", "remoteServices/getVehicleStatus/v4", body_dict=post_body, needs_keys=True, needs_auth=True)
  File "/usr/local/lib/python3.9/site-packages/pymazda/connection.py", line 158, in api_request
    return await self.__api_request_retry(method, uri, query_dict, body_dict, needs_keys, needs_auth, num_retries=0)
  File "/usr/local/lib/python3.9/site-packages/pymazda/connection.py", line 173, in __api_request_retry
    return await self.__send_api_request(method, uri, query_dict, body_dict, needs_keys, needs_auth)
  File "/usr/local/lib/python3.9/site-packages/pymazda/connection.py", line 245, in __send_api_request
    raise MazdaException("Request failed: " + response_json["error"])
pymazda.exceptions.MazdaException: Request failed: An update to Mazda app is required to continue
```

**Comment by pr0fetul** [comment]
@bdr99 - trying the code today I noticed the following output for vehicle_details and for vehicle_status: 

```
Car: 
{'vin': 'JMZxxxxxx', 
'id': 6000xxxxx, 
'nickname': 'CX5', 
'carlineCode': 'MAZDA CX-5', 
'carlineName': 'Mazda CX-5', 
'modelYear': '0000', 
'modelCode': 'KJP8', 
'modelName': 'Mazda CX-5', 
'automaticTransmission': False, 
'interiorColorCode': 'KF2', 
'interiorColorName': 'Tapițerie piele Nappa maro, scaune față-spate încălzite, scaune față ventilate', 
'exteriorColorCode': '45B', 
'exteriorColorName': 'Albastru Eternal', 
'isElectric': False}
```
automatic transmission is not correct - it should be true - I guess this needs to be discussed at the dealership :) 

```
Car Status: {'lastUpdatedTimestamp': '20220124163431', 
'latitude': 1111, 
'longitude': 111111, 
'positionTimestamp': '20220124163035', 
'fuelRemainingPercent': 33.0, 
'fuelDistanceRemainingKm': None, 
'odometerKm': 6326.9, 
'doors': 
{'driverDoorOpen': False, 
'passengerDoorOpen': False, 
'rearLeftDoorOpen': False, 
'rearRightDoorOpen': False, 
'trunkOpen': False, 
'hoodOpen': False, 
'fuelLidOpen': True}, 
'doorLocks': 
{'driverDoorUnlocked': False, 
'passengerDoorUnlocked': False, 
'rearLeftDoorUnlocked': False, 
'rearRightDoorUnlocked': False}, 
'windows': 
{'driverWindowOpen': False, 
'passengerWindowOpen': False, 
'rearLeftWindowOpen': False, 
'rearRightWindowOpen': False}, 
'hazardLightsOn': False, 
'tirePressure': 
{'frontLeftTirePressurePsi': None, 
'frontRightTirePressurePsi': None, 
'rearLeftTirePressurePsi': None, 
'rearRightTirePressurePsi': None}}
```
As we have outputs for doors, windows, could these be translated into sensors in HA as well? 
In order to read this, I changed the #APP_VERSION = "8.1.0" to APP_VERSION = "9.0.0" in connection.py and ran it (outside HA).

**Comment by HWiese1980** [comment]
> As we have outputs for doors, windows, could these be translated into sensors in HA as well?

I thought binary sensors for these were already on the roadmap... yeah, would be awesome to have these in HA too. 

Not the topic here though, just sayin 😘

**Comment by mragg** [comment]
Hi, at the moment I'm getting  "Request failed: An update to Mazda app is required to continue" requesting my mx30 - there's no fix (?) - I just didn't understand wether someone of you just fixed it ... 

(Since yesterday I'm on the first steps integrate the module into my homeautomation - I'm using fhem .. )

Martin

**Comment by HWiese1980** [comment]
I understand there's no official fix yet. Correct me if I'm wrong

**Comment by mragg** [comment]
One idea - in the android-app there today there is a new question "popup" after login to allow push notification. Perhaps that's the same in pymazda. After answering in the app there are no more questions in the app - it still is not working in pymazda - only an idea .. 

regards,
Martin

**Comment by bdr99** [comment]
Thanks to everyone who reported this issue. This happens every time Mazda releases a new version of their mobile app. They recently released version 8.1.1, and Mazda is now rejecting any connections coming from version 8.1.0 of the app. The library was identifying itself as version 8.1.0, which is why it broke.

I have incremented the mobile app version number in the code so that the library will present itself to Mazda's servers as version 8.1.1. It is fixed in https://github.com/bdr99/pymazda/commit/4725e661d44dec507e52b3051027a9a1b8c055b8 and released as version 0.3.2 of pymazda. It is also submitted as a PR to Home Assistant here: https://github.com/home-assistant/core/pull/65025

@pr0fetul @HWiese1980 I have a Home Assistant PR currently open (https://github.com/home-assistant/core/pull/64604) to add binary sensors to the Mazda integration. It's currently in the process of being reviewed by the HA team. It won't be in HA 2022.2, but hopefully it will be merged soon.

**Comment by Valdorama** [comment]
Given that this would happen whenever the Mazda app is updated, is there any way the integration could dynamically determine the latest app version? A quick Google suggests there may not be an official Google Play Store API for that info, but I found an unofficial one:

https://api-playstore.rajkumaar.co.in/version?id=com.interrait.mymazda

That gets you the version of the MyMazda app on the store. Haven't looked for an Apple app store equivalent.

Maybe the integration could try and get the latest version number and if not, fall back to a hard coded number?

**Comment by bdr99** [comment]
@Valdorama That's a good idea. I don't like the idea of using an unofficial API, but I'll explore alternatives. One idea I had was to add a static file in this repo that contains the version number. The library would fetch this file from github on startup and use that as the version number, falling back to the hard coded value if this fails. The file would still have to be kept to date, but at least users wouldn't need to wait for an HA update which could potentially take days/weeks. Let me know if you have any thoughts.

**Comment by Valdorama** [comment]
Yeah that would work well too. If it reads the file on startup, some extra advice in the error message would be useful i.e. "the integration is out of sync with the MyMazda app version...please reload the integration" or something to that effect. So when the integration is reloaded it fetches the updated github file.

**Comment by mragg** [comment]
@bdr99 Thanks a lot for your update - works again :-)

**Comment by HWiese1980** [comment]
Confirmed! Also works in HA, only need to copy the MyMazda integration from the HA core repository to `custom_components`, set `pymazda` version to 0.3.2 in the `manifest.json` and restart core.

**Comment by bdr99** [comment]
> Confirmed! Also works in HA, only need to copy the MyMazda integration from the HA core repository to `custom_components`, set `pymazda` version to 0.3.2 in the `manifest.json` and restart core.

If you do this, don't forget to delete it from `custom_components` after upgrading to HA 2022.2. Otherwise you will not receive any future improvements to the Mazda integration.

**Comment by HWiese1980** [comment]
Absolutely. Thanks for the heads-up! Oh and for the fix of course! You're doing a great job here!
