### ISSUE TITLE
Update is required to continue: June 2023

### ISSUE THREAD

**Issue by danlo315** [bdr99/pymazda#29]
Hi - getting the Mazda update required error:

2023-06-30 23:02:19.113 ERROR (MainThread) [homeassistant.components.mazda] Unknown error occurred during Mazda update request: Request failed: An update to Mazda app is required to continue

I'm on 2023.6.3, just started this morning.

**Comment by bdr99** [comment]
Thanks for letting me know. The fix has been submitted to HA in https://github.com/home-assistant/core/pull/95655 and it shold be included in HA 2023.7.0 when it releases on Wednesday.

**Comment by danlo315** [comment]
Hi @bdr99 - thanks for pushing this into 2023.7. Seeing that Mazda frequently breaks the integration, any thoughts on breaking this out of home assistant core and into something like a HACS? Using me as an example I try not to go to a .1 release and try and wait for . 2 before upgrading. Thanks!

**Comment by bdr99** [comment]
@danlo315 I don't think I want to remove the integration from HA core, since being in core makes the integration easier for people to use. However, you can always install the latest development version of core integration as a custom integration, achieving a similar effect, by following these steps:

1. In the [HA Core GitHub repo page](https://github.com/home-assistant/core), click the green “Code” button, then under "Local", click “Download ZIP”. It will download a file named core-dev.zip.
2. In the zip file, navigate to the path core-dev/homeassistant/components. Copy the mazda folder from here into your HA custom_components folder. If you don’t have a custom_components folder, you will need to create it. It should be located in the same folder as your configuration.yaml.
3. In the “mazda” folder within your custom_components folder, open the manifest.json file in a text editor. You will need to add a comma at the end of the `loggers` line, and then add a new line after it that says `"version": "1.0.0"`. So, after editing the file, the last few lines should look like this:

```
  "loggers": ["pymazda"],
  "version": "1.0.0"
}
```

4. Save your changes and restart HA. After you restart, it should load the custom Mazda integration instead of the built-in one, and you should have latest fixes. The custom integration will always override the built-in one if it is present, so make sure you delete it after you upgrade to an HA version that has the fixes built in. Otherwise, you won’t receive any future improvements to the Mazda integration since your custom one will always override it.

**Comment by danlo315** [comment]
Thank you for the helpful instructions. This is now working and good to
know I can do this on the future (and for other core integrations).
