### ISSUE TITLE
JavaScript Conversion

### ISSUE THREAD

**Issue by hufftheweevil** [bdr99/pymazda#4]
Not an issue, but a question:

I don't see any license for this repo. Is it open-source? If permitted, I would like to convert this to a JS library. I can attach credit, if necessary. Please let me know. Thank you

**Comment by bdr99** [comment]
It's funny you should ask, because this library actually started as a JS library, written in TypeScript. I ported it to Python so I could use it in Home Assistant, but I never actually published the JS version. I just published it, and you can find it here: [bdr99/node-mymazda](https://github.com/bdr99/node-mymazda) and on npm here: [node-mymazda](https://www.npmjs.com/package/node-mymazda)

The JS library is almost identical to this one, except for the naming conventions. I'm not sure what you were hoping to accomplish with a JS library, but if node-mymazda doesn't meet your needs, feel free to contribute to it! 😃

Regarding the license, both libraries are licensed under MIT. I added license files to both repos.

**Comment by hufftheweevil** [comment]
Sweet, this is going to save my so much headache trying to convert all those crypto functions. Thanks!

FYI, I'm going to be creating a Node-RED node that incorporates the API. I'll be sure to link back to the JS library for reference and attribution.

**Comment by bdr99** [comment]
Sounds awesome! Looking forward to it.

Yeah, the crypto functions were the hardest part when porting it from JS to Python. I'm glad you asked before porting it to JS. It would have been a shame if you redid the work I had already done.
